export const PROVINCES = [
  { value: "tehran", label: "تهران" },
  { value: "khorasan-razavi", label: "خراسان رضوی" },
  { value: "isfahan", label: "اصفهان" },
  { value: "fars", label: "فارس" },
  { value: "khuzestan", label: "خوزستان" },
  { value: "azarbaijan-sharghi", label: "آذربایجان شرقی" },
  { value: "azarbaijan-gharbi", label: "آذربایجان غربی" },
  { value: "gilan", label: "گیلان" },
  { value: "mazandaran", label: "مازندران" },
  { value: "kerman", label: "کرمان" },
  { value: "sistan-baluchestan", label: "سیستان و بلوچستان" },
  { value: "lorestan", label: "لرستان" },
  { value: "hmedan", label: "همدان" },
  { value: "golestan", label: "گلستان" },
  { value: "kermanshah", label: "کرمانشاه" },
  { value: "hormozgan", label: "هرمزگان" },
  { value: "markazi", label: "مرکزی" },
  { value: "ardabil", label: "اردبیل" },
  { value: "qom", label: "قم" },
  { value: "yazd", label: "یزد" },
  { value: "zanjan", label: "زنجان" },
  { value: "chaharmahal-bakhtiari", label: "چهارمحال و بختیاری" },
  { value: "kohgiluyeh-boyer", label: "کهگیلویه و بویراحمد" },
  { value: "bushehr", label: "بوشهر" },
  { value: "semnan", label: "سمنان" },
  { value: "ilam", label: "ایلام" },
  { value: "qazvin", label: "قزوین" },
  { value: "khorasan-shomali", label: "خراسان شمالی" },
  { value: "khorasan-jonubi", label: "خراسان جنوبی" },
  { value: "alborz", label: "البرز" },
  { value: "other", label: "سایر" },
] as const;

export const JOBS = [
  { value: "architect", label: "معمار" },
  { value: "interior-designer", label: "طراح داخلی" },
  { value: "graphic-designer", label: "طراح گرافیک" },
  { value: "ui-designer", label: "طراح رابط کاربری" },
  { value: "ux-designer", label: "طراح تجربه کاربری" },
  { value: "product-designer", label: "طراح محصول" },
  { value: "fashion-designer", label: "طراح مد و لباس" },
  { value: "industrial-designer", label: "طراح صنعتی" },
  { value: "animator", label: "انیماتور" },
  { value: "illustrator", label: "تصویرساز" },
  { value: "photographer", label: "عکاس" },
  { value: "videographer", label: "فیلمبردار" },
  { value: "motion-designer", label: "موشن طراح" },
  { value: "visual-effects", label: "جلوه‌های ویژه" },
  { value: "calligrapher", label: "خوشنویس" },
  { value: "painter", label: "نقاش" },
  { value: "sculptor", label: "مجسمه‌ساز" },
  { value: "potter", label: "سفالگر" },
  { value: "jewelry-designer", label: "طراح جواهرات" },
  { value: "textile-designer", label: "طراح پارچه" },
  { value: "game-developer", label: "توسعه‌دهنده بازی" },
  { value: "frontend-developer", label: "توسعه‌دهنده فرانت‌اند" },
  { value: "backend-developer", label: "توسعه‌دهنده بک‌اند" },
  { value: "mobile-developer", label: "توسعه‌دهنده موبایل" },
  { value: "data-scientist", label: "دانشمند داده" },
  { value: "ai-engineer", label: "مهندس هوش مصنوعی" },
  { value: "content-creator", label: "تولیدکننده محتوا" },
  { value: "social-media-manager", label: "مدیر رسانه اجتماعی" },
  { value: "digital-marketer", label: "بازاریاب دیجیتال" },
  { value: "seo-specialist", label: "متخصص سئو" },
  { value: "writer", label: "نویسنده" },
  { value: "editor", label: "ویراستار" },
  { value: "translator", label: "مترجم" },
  { value: "musician", label: "موسیقی‌دان" },
  { value: "composer", label: "آهنگساز" },
  { value: "singer", label: "خواننده" },
  { value: "actor", label: "بازیگر" },
  { value: "director", label: "کارگردان" },
  { value: "chef", label: "آشپز" },
  { value: "baker", label: "قناد" },
  { value: "barista", label: "باریستا" },
  { value: "makeup-artist", label: "آرایشگر" },
  { value: "hairdresser", label: "موآرای" },
  { value: "nail-artist", label: "ناخن‌کار" },
  { value: "tattoo-artist", label: "تتو آرتیست" },
  { value: "florist", label: "گل‌آرا" },
  { value: "event-planner", label: "برنامه‌ریز رویداد" },
  { value: "entrepreneur", label: "کارآفرین" },
  { value: "student", label: "دانشجو / دانش‌آموز" },
  { value: "other", label: "سایر" },
] as const;

export const PERSIAN_MONTHS = [
  "فروردین",
  "اردیبهشت",
  "خرداد",
  "تیر",
  "مرداد",
  "شهریور",
  "مهر",
  "آبان",
  "آذر",
  "دی",
  "بهمن",
  "اسفند",
];
